//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_List
    {
        public string Resource_Id { get; set; }
        public string Resource_Name { get; set; }
        public int Availability { get; set; }
        public System.DateTime Start_Date { get; set; }
        public System.DateTime End_Date { get; set; }
    }
}
